# Generated by Django 3.1.7 on 2021-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='id',
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/avtatco', max_length=500),
        ),
        migrations.AddField(
            model_name='artist',
            name='job_title',
            field=models.CharField(default='Tattoo Artist', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='specialty_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='specialty_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='specialty_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='art',
            name='slug',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(max_length=250),
        ),
    ]
